---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: ingress-config
  namespace: nginx
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.dapr-monitoring.svc.cluster.local:9411/api/v2/spans"
  secrets:
    scopes:
      - storeName: kubernetes
        defaultAccess: deny
        allowedSecrets: ["dapr-api-token"]